name       : projectlibre
version    : 1.9.3
release    : 8
source     :
    - git|https://git.code.sf.net/p/projectlibre/code : 20814e88dc83694f9fc6780c2550ca5c8a87aa16
license    : CPAL-1.0
component  : office
homepage   : https://www.projectlibre.com/
summary    : The open source replacement of Microsoft Project
description: |
    ProjectLibre is the leading open source alternative to Microsoft Project. It has been downloaded over 4,300,000 times in over 200 countries and has won InfoWorld "Best of Open Source" award. ProjectLibre is compatible with Microsoft Project 2003, 2007, 2010, 2013 and 2016 files.
builddeps  :
    - apache-ant
    - openjdk-11
rundeps    :
    - openjdk-11
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-11
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-jdk-search-and-use-java-11.patch
build      : |
    cd projectlibre_build
    ant dir
install    : |
    pushd projectlibre_build/dist
    install -Dm00644 lib/*.jar -t $installdir/usr/share/projectlibre/lib
    install -Dm00644 projectlibre.jar -t $installdir/usr/share/projectlibre
    popd

    pushd projectlibre_build/resources
    install -Dm00755 projectlibre -t $installdir/usr/bin
    install -Dm00644 projectlibre.desktop -t $installdir/usr/share/applications
    install -Dm00644 projectlibre.png -t $installdir/usr/share/pixmaps
    install -Dm00644 projectlibre.xml -t $installdir/usr/share/mime/packages
    popd
