name       : projectlibre
version    : 1.9.0
release    : 3
source     :
    - git|https://git.code.sf.net/p/projectlibre/code : 9b5c2f988e913fa5de4284a3e18c745c15910ca4
license    : CPAL-1.0
component  : office
summary    : The open source replacement of Microsoft Project
description: |
    ProjectLibre is the leading open source alternative to Microsoft Project.
    It has been downloaded over 2,700,000 times in over 200 countries and has
    won InfoWorld "Best of Open Source" award. ProjectLibre is compatible with
    Microsoft Project 2003, 2007 and 2010 files.
builddeps  : 
    - apache-ant
rundeps    :
    - openjdk-8
build      : |
    cd projectlibre_build
    ant dir
install    : |
    cd projectlibre_build

    pushd dist
    install -D -m00644 lib/*.jar -t $installdir/usr/share/projectlibre/lib
    install -m00644 projectlibre.jar -t $installdir/usr/share/projectlibre
    popd

    pushd resources
    install -D -m00755 projectlibre -t $installdir/usr/bin
    install -D -m00644 projectlibre.desktop -t $installdir/usr/share/applications
    install -D -m00644 projectlibre.png -t $installdir/usr/share/pixmaps
    install -D -m00644 projectlibre.xml -t $installdir/usr/share/mime/packages
    popd
