name       : projectlibre
version    : 1.9.1
release    : 6
source     :
    - git|https://git.code.sf.net/p/projectlibre/code : a4f188f47459206c8c30219727f13f8ca2735cc7
homepage   : https://www.projectlibre.com/
license    : CPAL-1.0
component  : office
summary    : The open source replacement of Microsoft Project
description: |
    ProjectLibre is the leading open source alternative to Microsoft Project. It has been downloaded over 4,300,000 times in over 200 countries and has won InfoWorld "Best of Open Source" award. ProjectLibre is compatible with Microsoft Project 2003, 2007, 2010, 2013 and 2016 files.
builddeps  :
    - apache-ant
rundeps    :
    - openjdk-11
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-jdk-search-and-use-java-11.patch
build      : |
    cd projectlibre_build
    ant dir
install    : |
    cd projectlibre_build

    pushd dist
    install -Dm00644 lib/*.jar -t $installdir/usr/share/projectlibre/lib
    install -Dm00644 projectlibre.jar -t $installdir/usr/share/projectlibre
    popd

    pushd resources
    install -Dm00755 projectlibre -t $installdir/usr/bin
    install -Dm00644 projectlibre.desktop -t $installdir/usr/share/applications
    install -Dm00644 projectlibre.png -t $installdir/usr/share/pixmaps
    install -Dm00644 projectlibre.xml -t $installdir/usr/share/mime/packages
    popd
